// <auto-generated />
using System;
using EFcoreProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFcoreProject.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20260409143120_change-courseStudent-tableName")]
    partial class changecourseStudenttableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("EFcoreProject.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Duration = 40,
                            InstructorId = 1,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Duration = 30,
                            InstructorId = 2,
                            Name = "Calculus"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Duration = 35,
                            InstructorId = 3,
                            Name = "Physics 1"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Duration = 45,
                            InstructorId = 4,
                            Name = "Organic Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Duration = 32,
                            InstructorId = 5,
                            Name = "Cell Biology"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            Duration = 28,
                            InstructorId = 6,
                            Name = "English Literature"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            Duration = 30,
                            InstructorId = 7,
                            Name = "Modern History"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            Duration = 36,
                            InstructorId = 8,
                            Name = "Microeconomics"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            Duration = 20,
                            InstructorId = 9,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            Duration = 22,
                            InstructorId = 10,
                            Name = "Music Theory"
                        });
                });

            modelBuilder.Entity("EFcoreProject.Models.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            Title = "Intro to C#"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Date = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            Title = "Limits and Continuity"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Date = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 3,
                            Title = "Mechanics"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Date = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 4,
                            Title = "Hydrocarbons"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Date = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 5,
                            Title = "Cell Structure"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            Date = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 6,
                            Title = "Shakespeare Overview"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            Date = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 7,
                            Title = "WW2 Events"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 8,
                            Date = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 8,
                            Title = "Supply & Demand"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 9,
                            Date = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 9,
                            Title = "Figure Drawing"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            Date = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 10,
                            Title = "Harmony Basics"
                        });
                });

            modelBuilder.Entity("EFcoreProject.Models.CourseSessionAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseSessionAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseSessionId = 1,
                            Grade = 90,
                            Notes = "Good",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseSessionId = 2,
                            Grade = 85,
                            Notes = "Very Good",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseSessionId = 3,
                            Grade = 95,
                            Notes = "Excellent",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseSessionId = 4,
                            Grade = 88,
                            Notes = "Well Done",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseSessionId = 5,
                            Grade = 76,
                            Notes = "Satisfactory",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseSessionId = 6,
                            Grade = 82,
                            Notes = "Good",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            CourseSessionId = 7,
                            Grade = 79,
                            Notes = "Needs Improvement",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            CourseSessionId = 8,
                            Grade = 91,
                            Notes = "Very Good",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            CourseSessionId = 9,
                            Grade = 87,
                            Notes = "Good",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            CourseSessionId = 10,
                            Grade = 93,
                            Notes = "Excellent",
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("EFcoreProject.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Building A",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Building B",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Building C",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Building D",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Building E",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Building F",
                            Name = "English"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Building G",
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Building H",
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Building I",
                            Name = "Art"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Building J",
                            Name = "Music"
                        });
                });

            modelBuilder.Entity("EFcoreProject.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Phone = "01012345678"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 2,
                            FirstName = "Mona",
                            LastName = "Hassan",
                            Phone = "01112345678"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 3,
                            FirstName = "Khaled",
                            LastName = "Ibrahim",
                            Phone = "01212345678"
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 4,
                            FirstName = "Lina",
                            LastName = "Youssef",
                            Phone = "01098765432"
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 5,
                            FirstName = "Youssef",
                            LastName = "Saeed",
                            Phone = "01155556666"
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 6,
                            FirstName = "Dina",
                            LastName = "Farid",
                            Phone = "01233334444"
                        },
                        new
                        {
                            ID = 7,
                            DepartmentId = 7,
                            FirstName = "Ola",
                            LastName = "Mahmoud",
                            Phone = "01022223333"
                        },
                        new
                        {
                            ID = 8,
                            DepartmentId = 8,
                            FirstName = "Samir",
                            LastName = "Nabil",
                            Phone = "01111112222"
                        },
                        new
                        {
                            ID = 9,
                            DepartmentId = 9,
                            FirstName = "Rana",
                            LastName = "Fahmy",
                            Phone = "01244445555"
                        },
                        new
                        {
                            ID = 10,
                            DepartmentId = 10,
                            FirstName = "Tamer",
                            LastName = "Sami",
                            Phone = "01066667777"
                        });
                });

            modelBuilder.Entity("EFcoreProject.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Omar",
                            LastName = "Tarek",
                            Phone = "01212345678"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sara",
                            LastName = "Gamal",
                            Phone = "01512345678"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ali",
                            LastName = "Hassan",
                            Phone = "01187654321"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Mariam",
                            LastName = "Saeed",
                            Phone = "01010101010"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Hassan",
                            LastName = "Kamal",
                            Phone = "01120202020"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Nora",
                            LastName = "Fadel",
                            Phone = "01230303030"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Yara",
                            LastName = "Adel",
                            Phone = "01040404040"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Karim",
                            LastName = "Ibraheem",
                            Phone = "01150505050"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Dalia",
                            LastName = "Mostafa",
                            Phone = "01260606060"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Mostafa",
                            LastName = "Nagy",
                            Phone = "01070707070"
                        });
                });

            modelBuilder.Entity("EFcoreProject.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 4
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 5
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 6
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 7
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 8
                        },
                        new
                        {
                            StudentId = 9,
                            CourseId = 9
                        },
                        new
                        {
                            StudentId = 10,
                            CourseId = 10
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("EFcoreProject.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFcoreProject.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFcoreProject.Models.Course", b =>
                {
                    b.HasOne("EFcoreProject.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFcoreProject.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EFcoreProject.Models.CourseSession", b =>
                {
                    b.HasOne("EFcoreProject.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFcoreProject.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EFcoreProject.Models.CourseSessionAttendance", b =>
                {
                    b.HasOne("EFcoreProject.Models.CourseSession", "CourseSession")
                        .WithMany("courseSessionAttendances")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFcoreProject.Models.Student", "Student")
                        .WithMany("CourseSessionAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFcoreProject.Models.Department", b =>
                {
                    b.HasOne("EFcoreProject.Models.Instructor", "Manager")
                        .WithOne("DepartmentManaged")
                        .HasForeignKey("EFcoreProject.Models.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EFcoreProject.Models.Instructor", b =>
                {
                    b.HasOne("EFcoreProject.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFcoreProject.Models.StudentCourse", b =>
                {
                    b.HasOne("EFcoreProject.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFcoreProject.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFcoreProject.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("EFcoreProject.Models.CourseSession", b =>
                {
                    b.Navigation("courseSessionAttendances");
                });

            modelBuilder.Entity("EFcoreProject.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("EFcoreProject.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("DepartmentManaged");
                });

            modelBuilder.Entity("EFcoreProject.Models.Student", b =>
                {
                    b.Navigation("CourseSessionAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
